[tool.poetry]
name = "mac_cleanup"
version = "2.2.4"
description = "Python cleanup script for macOS"
license = "Apache-2.0"
authors = [ "Drugsosos <44712637+Drugsosos@users.noreply.github.com>" ]
readme = "README.md"
homepage = "https://github.com/mac-cleanup/mac-cleanup-py"
repository = "https://github.com/mac-cleanup/mac-cleanup-py"
keywords = [ "macos", "script", "cleanup", "cleaner" ]
classifiers = [ "Environment :: Console", "Operating System :: MacOS", ]

include = [ "LICENSE" ]
exclude = [ "mac_cleanup/__main__.py", "mac_cleanup/py.typed" ]

[tool.poetry.urls]
"Documentation" = "https://github.com/mac-cleanup/mac-cleanup-py#install-automatically"
"Issue Tracker" = "https://github.com/mac-cleanup/mac-cleanup-py/issues"


[tool.poetry.dependencies]
python = ">=3.7,<3.12"
rich = "^12.2.0"
toml = "^0.10.2"
inquirer = "^2.10.0"
attrs = "^22.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
tox = "^3.25.1"
flake8 = "^5.0.4"
Flake8-pyproject = "^1.1.0"
mypy = "^0.971"
pytest-cov = "^3.0.0"
types-toml = "^0.10.8"

[tool.poetry.scripts]
mac-cleanup = "mac_cleanup:main"

[options.package_data]
mac_cleanup = "py.typed"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.flake8]
max-line-length = 120
per-file-ignores = [
    "default_modules.py, cli.py, test_utils.py:F403, F405",
]
count = true

[tool.mypy]
python_version = "3.10"
platform = "darwin"
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
show_error_codes = true
strict_equality = true
exclude = "default_modules.py"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=mac_cleanup"
testpaths = [ "tests" ]